# xorg-presence default config example

# if your window title doesnt match an existing asset \
# set it to an existing default asset
[defaults]
small_image = ""

# here you can rename your window title to match whatever \
# your app asset is titled
[aliases]
firefox = "browser"
zen = "browser"
emacs = "editor"
wezterm = "terminal"
alacritty = "terminal"

# empty workspaces show up as 'unkown' remove if \
# you dont mind having your window title show up as 'unkown'
[unkown]
title = "Empty Workspace"
small_image = "gnu"

[apps.browser]
small_image = "zen"

# you can also set the large image instead of it defaulting \
# to your WM's logo
[apps.editor]
large_image = "emacs"
small_image = "tux"

[apps.terminal]
default_large_image = "archlinux"
default_small_image = "terminal"