# xorg-presence default config example

# default option: wm = window manager name
[defaults]
details = "app" # can be "app", "class", or "title"
large_image = "wm"
small_image = ""

# map a window's class to an app table
[aliases]
firefox = "browser"
zen = "browser"
emacs = "editor"
"org.wezfurlong.wezterm" = "terminal"
alacritty = "terminal"

# empty workspaces show up as 'unknown' (remove if you want the title to show)
[unknown]
name = "Empty Workspace"
small_image = "gnu"

# apps
[apps.browser]
small_image = "zen"

[apps.editor]
large_image = "emacs"
small_image = "tux"

[apps.terminal]
large_image = "archlinux"
small_image = "terminal"
